version: '3'

volumes:
  scylla-data-0:
  scylla-data-1:

services:
  scylla-0:
    image: scylladb/scylla
    container_name: scylla-0
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - scylla-data-0:/var/lib/scylla
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    image: ghcr.io/karitham/idiot/api
    container_name: api
    restart: always
    ports:
      - "7667:7667"
    environment:
      CASSANDRA_IPS: scylla-0:9042
      PORT: 7667
    depends_on:
      scylla-0: 
        condition: service_healthy
