// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package models

import (
	"github.com/scylladb/gocqlx/v2/table"
	"time"
)

// Table models.
var (
	Alerts = table.New(table.Metadata{
		Name: "alerts",
		Columns: []string{
			"alert_status",
			"alert_type",
			"alert_value",
			"device_id",
			"id",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	Devices = table.New(table.Metadata{
		Name: "devices",
		Columns: []string{
			"id",
			"name",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	Keys = table.New(table.Metadata{
		Name: "keys",
		Columns: []string{
			"id",
			"private_key",
			"public_key",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	Migrations = table.New(table.Metadata{
		Name: "migrations",
		Columns: []string{
			"content",
			"id",
			"time",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	SensorReadings = table.New(table.Metadata{
		Name: "sensor_readings",
		Columns: []string{
			"iot_id",
			"time",
			"value",
		},
		PartKey: []string{
			"iot_id",
		},
		SortKey: []string{
			"time",
		},
	})

	Sessions = table.New(table.Metadata{
		Name: "sessions",
		Columns: []string{
			"id",
			"permissions",
			"user_id",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	Users = table.New(table.Metadata{
		Name: "users",
		Columns: []string{
			"email",
			"id",
			"name",
			"password",
			"permissions",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{
			"email",
		},
	})

	UsersEmailIdxIndex = table.New(table.Metadata{
		Name: "users_email_idx_index",
		Columns: []string{
			"email",
			"id",
			"idx_token",
		},
		PartKey: []string{
			"email",
		},
		SortKey: []string{
			"idx_token",
			"id",
		},
	})

	WebpushSubscriptions = table.New(table.Metadata{
		Name: "webpush_subscriptions",
		Columns: []string{
			"subscription",
			"user_id",
		},
		PartKey: []string{
			"user_id",
		},
		SortKey: []string{},
	})
)

type AlertsStruct struct {
	AlertStatus string
	AlertType   string
	AlertValue  string
	DeviceId    string
	Id          string
}
type DevicesStruct struct {
	Id   string
	Name string
}
type KeysStruct struct {
	Id         string
	PrivateKey []byte
	PublicKey  []byte
}
type MigrationsStruct struct {
	Content string
	Id      int32
	Time    [16]byte
}
type SensorReadingsStruct struct {
	IotId string
	Time  time.Time
	Value []byte
}
type SessionsStruct struct {
	Id          string
	Permissions []string
	UserId      string
}
type UsersStruct struct {
	Email       string
	Id          string
	Name        string
	Password    string
	Permissions []string
}
type UsersEmailIdxIndexStruct struct {
	Email    string
	Id       string
	IdxToken int64
}
type WebpushSubscriptionsStruct struct {
	Subscription [][]byte
	UserId       string
}
