// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package models

import (
	"github.com/scylladb/gocqlx/v2/table"
)

// Table models.
var (
	Migrations = table.New(table.Metadata{
		Name: "migrations",
		Columns: []string{
			"content",
			"time",
		},
		PartKey: []string{
			"content",
		},
		SortKey: []string{
			"time",
		},
	})

	Sessions = table.New(table.Metadata{
		Name: "sessions",
		Columns: []string{
			"id",
			"permissions",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	Users = table.New(table.Metadata{
		Name: "users",
		Columns: []string{
			"email",
			"id",
			"name",
			"password",
			"permissions",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{
			"email",
		},
	})

	UsersEmailIdxIndex = table.New(table.Metadata{
		Name: "users_email_idx_index",
		Columns: []string{
			"email",
			"id",
			"idx_token",
		},
		PartKey: []string{
			"email",
		},
		SortKey: []string{
			"idx_token",
			"id",
		},
	})
)

type MigrationsStruct struct {
	Content string
	Time    [16]byte
}
type SessionsStruct struct {
	Id          string
	Permissions []string
}
type UsersStruct struct {
	Email       string
	Id          string
	Name        string
	Password    string
	Permissions []string
}
type UsersEmailIdxIndexStruct struct {
	Email    string
	Id       string
	IdxToken int64
}
