// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package models

import (
	"github.com/scylladb/gocqlx/v2/table"
)

// Table models.
var (
	Users = table.New(table.Metadata{
		Name: "users",
		Columns: []string{
			"email",
			"id",
			"name",
			"password",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{
			"email",
		},
	})

	UsersEmailIdxIndex = table.New(table.Metadata{
		Name: "users_email_idx_index",
		Columns: []string{
			"email",
			"id",
			"idx_token",
		},
		PartKey: []string{
			"email",
		},
		SortKey: []string{
			"idx_token",
			"id",
		},
	})
)

type UsersStruct struct {
	Email    string
	Id       string
	Name     string
	Password string
}
type UsersEmailIdxIndexStruct struct {
	Email    string
	Id       string
	IdxToken int64
}
