VERSION 0.7
FROM golang:1.20.4-alpine
WORKDIR /go-workdir

download-deps:
    RUN go install github.com/discord-gophers/goapi-gen@v0.3.0

api:
    FROM +download-deps

    COPY go.* ./
    RUN go mod download

    COPY openapi.yml ./
    
    RUN goapi-gen --out types.gen.go --generate types --package api -- openapi.yml
    RUN goapi-gen --out srv.gen.go --generate server --package api -- openapi.yml

    SAVE ARTIFACT *.gen.go AS LOCAL ./httpd/api/

db:
    LOCALLY
    RUN go install github.com/scylladb/gocqlx/v2/cmd/schemagen@latest
    RUN "$HOME/go/bin/schemagen" -output store/models -keyspace idiot -cluster localhost:9042

docs:
    FROM node:20-alpine
    RUN npm install -g widdershins
    COPY openapi.yml ./
    RUN widdershins openapi.yml -o docs.md --language_tabs 'javascript:JS' 'shell:Shell'
    SAVE ARTIFACT docs.md AS LOCAL docs.md
