name: build-api

on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: karitham
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./api
          tags: ghcr.io/karitham/idiot/api:${{ github.sha }},ghcr.io/karitham/idiot/api:latest
          cache-from: type=registry,ref=ghcr.io/karitham/idiot
          cache-to: type=inline
