name: build-proxy

on:
  push:
    branches: [ master ]
    paths:
      - 'media-proxy/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: karitham
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./media-proxy
          tags: ghcr.io/karitham/idiot/media-proxy:${{ github.sha }},ghcr.io/karitham/idiot/media-proxy:latest
          cache-from: type=registry,ref=ghcr.io/karitham/idiot
          platforms: linux/amd64,linux/arm64
          cache-to: type=inline
